# Generated by Django 5.1.6 on 2025-03-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_remove_habit_completion_dates_remove_habit_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
